import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import styles from '../styles/Home.module.css';

const About = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.grid}>
                    <Link href="/about">
                        <a className={styles.card}>About</a>
                    </Link>
                    <Link href="/contact">
                        <a className={styles.card}>contact</a>
                    </Link>
                    <Link href="/">
                        <a className={styles.card}>Home</a>
                    </Link>
                </div>
            </main>
        </div>
    );
};

export default About;
